application: your_app_id
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: pycrypto
  version: "2.6"

handlers:

- url: /
  script: index.py
  secure: optional

- url: /static.html
  script: login.py
  secure: optional

- url: /cron_purge.py
  script: cron_purge.py
  login: admin
