application: your-id
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: pycrypto
  version: "2.6"

handlers:

- url: /
  script: index.py
  secure: optional

- url: /login.html
  script: login.py
  secure: optional

